export const REPAIR_TECHNICIANS = ["Alex K.", "Maria S.", "James T.", "Chen W.", "Priya R."];
export const CURRENT_USER = "Alex K.";

export const mockTickets = [
  {
    id: "tk_psu_denver",
    ticketNumber: "TK-0042",
    category: "miner",
    status: "open",
    urgent: true,
    component: "PSU",
    diagnosis: "PSU fault — 612 miners, racks A3–A9",
    minerIdentifier: null,
    assigneeName: null,
    siteName: "Denver",
    buildingName: "Buildings A–B",
    rackLabel: "",
    zone: "—",
    groupLabel: "",
    commentCount: 0,
    partsCount: 0,
    age: "2m",
    alertId: "ntf_hw_psu_denver",
    alertLabel: "612 PSU faults — Denver",
  },
  {
    id: "tk_psu_austin",
    ticketNumber: "TK-0043",
    category: "miner",
    status: "open",
    urgent: true,
    component: "PSU",
    diagnosis: "PSU fault — 281 miners, racks C1–C4",
    minerIdentifier: null,
    assigneeName: null,
    siteName: "Austin",
    buildingName: "Building C",
    rackLabel: "",
    zone: "—",
    groupLabel: "",
    commentCount: 0,
    partsCount: 0,
    age: "2m",
    alertId: "ntf_hw_psu_austin",
    alertLabel: "281 PSU faults — Austin",
  },
  {
    id: "tk_psu_miami",
    ticketNumber: "TK-0044",
    category: "miner",
    status: "open",
    urgent: true,
    component: "PSU",
    diagnosis: "PSU fault — 107 miners, racks A1–A2",
    minerIdentifier: null,
    assigneeName: null,
    siteName: "Miami",
    buildingName: "Building A",
    rackLabel: "",
    zone: "—",
    groupLabel: "",
    commentCount: 0,
    partsCount: 0,
    age: "2m",
    alertId: "ntf_hw_psu_miami",
    alertLabel: "107 PSU faults — Miami",
  },
  {
    id: "tk_m0001_psu",
    ticketNumber: "TK-0031",
    category: "miner",
    status: "in_progress",
    urgent: false,
    component: "PSU",
    diagnosis: "PSU fault (code 1012) — recommend replacement",
    minerIdentifier: "M0001",
    assigneeName: "Alex K.",
    siteName: "Denver",
    buildingName: "Building A",
    rackLabel: "R07",
    zone: "Zone A",
    groupLabel: "Production",
    commentCount: 1,
    partsCount: 1,
    age: "1h 35m",
    alertId: "ntf_hw_1",
    alertLabel: "M0001 PSU fault (code 1012)",
  },
  {
    id: "1",
    ticketNumber: "TK-0001",
    category: "miner",
    status: "open",
    urgent: true,
    component: "Hashboard",
    diagnosis: "Hashboard not detected",
    minerIdentifier: "M0012",
    assigneeName: null,
    siteName: "Denver",
    buildingName: "Building 1",
    rackLabel: "R03",
    zone: "Zone A",
    groupLabel: "Production",
    commentCount: 0,
    partsCount: 0,
    age: "3d 14h",
  },
  {
    id: "2",
    ticketNumber: "TK-0002",
    category: "miner",
    status: "in_progress",
    urgent: false,
    component: "Fan",
    diagnosis: "Fan speed below threshold",
    minerIdentifier: "M0045",
    assigneeName: "Alex K.",
    siteName: "Denver",
    buildingName: "Building 2",
    rackLabel: "R07",
    zone: "Zone B",
    groupLabel: "Production",
    commentCount: 2,
    partsCount: 1,
    age: "0h",
  },
  {
    id: "3",
    ticketNumber: "TK-0003",
    category: "miner",
    status: "open",
    urgent: true,
    component: "PSU",
    diagnosis: "PSU overvoltage fault",
    minerIdentifier: "M0089",
    assigneeName: null,
    siteName: "Austin",
    buildingName: "Building 1",
    rackLabel: "R12",
    zone: "Zone A",
    groupLabel: "Production",
    commentCount: 0,
    partsCount: 0,
    age: "2h",
  },
  {
    id: "4",
    ticketNumber: "TK-0004",
    category: "miner",
    status: "in_progress",
    urgent: false,
    component: "Fan",
    diagnosis: "Overheating — thermal throttle active",
    minerIdentifier: "M0023",
    assigneeName: "Maria S.",
    siteName: "Denver",
    buildingName: "Building 3",
    rackLabel: "R01",
    zone: "Zone C",
    groupLabel: "Testing",
    commentCount: 1,
    partsCount: 0,
    age: "5h",
  },
  {
    id: "5",
    ticketNumber: "TK-0005",
    category: "miner",
    status: "on_hold",
    urgent: false,
    component: "Hashboard",
    diagnosis: "Hashboard underperforming",
    minerIdentifier: "M0067",
    assigneeName: "James T.",
    siteName: "Austin",
    buildingName: "Building 2",
    rackLabel: "R09",
    zone: "Zone B",
    groupLabel: "Production",
    commentCount: 3,
    partsCount: 2,
    age: "8h",
  },
  {
    id: "6",
    ticketNumber: "TK-0006",
    category: "miner",
    status: "sent_to_vendor",
    urgent: false,
    component: "Control Board",
    diagnosis: "Control board unresponsive",
    minerIdentifier: "M0101",
    assigneeName: "Chen W.",
    siteName: "Miami",
    buildingName: "Building 2",
    rackLabel: "R15",
    zone: "Zone A",
    groupLabel: "Production",
    commentCount: 1,
    partsCount: 0,
    age: "14h",
  },
  {
    id: "7",
    ticketNumber: "TK-0007",
    category: "infrastructure",
    status: "open",
    urgent: true,
    component: "Electrical",
    diagnosis: "PDU breaker tripped",
    minerIdentifier: null,
    assigneeName: null,
    siteName: "Denver",
    buildingName: "Building 1",
    rackLabel: "",
    zone: "Zone 1",
    groupLabel: "",
    commentCount: 0,
    partsCount: 0,
    age: "1d 3h",
  },
  {
    id: "8",
    ticketNumber: "TK-0008",
    category: "infrastructure",
    status: "in_progress",
    urgent: false,
    component: "Network",
    diagnosis: "Switch port flapping",
    minerIdentifier: null,
    assigneeName: "Priya R.",
    siteName: "Austin",
    buildingName: "Building 3",
    rackLabel: "",
    zone: "Zone 2",
    groupLabel: "",
    commentCount: 2,
    partsCount: 0,
    age: "1d 8h",
  },
  {
    id: "9",
    ticketNumber: "TK-0009",
    category: "infrastructure",
    status: "open",
    urgent: false,
    component: "HVAC",
    diagnosis: "Cooling loop pressure drop",
    minerIdentifier: null,
    assigneeName: null,
    siteName: "Miami",
    buildingName: "Building 2",
    rackLabel: "",
    zone: "Zone 1",
    groupLabel: "",
    commentCount: 0,
    partsCount: 0,
    age: "2d 5h",
  },
  {
    id: "10",
    ticketNumber: "TK-0010",
    category: "miner",
    status: "open",
    urgent: false,
    component: "Fan",
    diagnosis: "Fan speed below threshold",
    minerIdentifier: "M0134",
    assigneeName: null,
    siteName: "Denver",
    buildingName: "Building 5",
    rackLabel: "R22",
    zone: "Zone D",
    groupLabel: "Production",
    commentCount: 0,
    partsCount: 0,
    age: "3d 14h",
  },
  {
    id: "11",
    ticketNumber: "TK-0011",
    category: "miner",
    status: "in_progress",
    urgent: true,
    component: "PSU",
    diagnosis: "PSU overvoltage fault",
    minerIdentifier: "M0156",
    assigneeName: "Alex K.",
    siteName: "Denver",
    buildingName: "Building 4",
    rackLabel: "R18",
    zone: "Zone A",
    groupLabel: "Production",
    commentCount: 1,
    partsCount: 1,
    age: "4d 2h",
  },
  {
    id: "12",
    ticketNumber: "TK-0012",
    category: "infrastructure",
    status: "on_hold",
    urgent: false,
    component: "Cleaning",
    diagnosis: "Scheduled rack cleaning",
    minerIdentifier: null,
    assigneeName: "Maria S.",
    siteName: "Denver",
    buildingName: "Building 2",
    rackLabel: "",
    zone: "Zone 3",
    groupLabel: "",
    commentCount: 0,
    partsCount: 0,
    age: "5d 18h",
  },
  {
    id: "13",
    ticketNumber: "TK-0013",
    category: "miner",
    status: "open",
    urgent: false,
    component: "Hashboard",
    diagnosis: "Hashboard not detected",
    minerIdentifier: "M0078",
    assigneeName: null,
    siteName: "Austin",
    buildingName: "Building 4",
    rackLabel: "R05",
    zone: "Zone B",
    groupLabel: "Production",
    commentCount: 0,
    partsCount: 0,
    age: "6d 1h",
  },
  {
    id: "14",
    ticketNumber: "TK-0014",
    category: "infrastructure",
    status: "in_progress",
    urgent: true,
    component: "Electrical",
    diagnosis: "UPS battery replacement due",
    minerIdentifier: null,
    assigneeName: "Chen W.",
    siteName: "Miami",
    buildingName: "Building 10",
    rackLabel: "",
    zone: "Zone 1",
    groupLabel: "",
    commentCount: 4,
    partsCount: 1,
    age: "7d 9h",
  },
  {
    id: "15",
    ticketNumber: "TK-0015",
    category: "miner",
    status: "open",
    urgent: false,
    component: "Fan",
    diagnosis: "Overheating — thermal throttle active",
    minerIdentifier: "M0201",
    assigneeName: null,
    siteName: "Denver",
    buildingName: "Building 6",
    rackLabel: "R11",
    zone: "Zone C",
    groupLabel: "Production",
    commentCount: 0,
    partsCount: 0,
    age: "10d 4h",
  },
  {
    id: "16",
    ticketNumber: "TK-0016",
    category: "infrastructure",
    status: "open",
    urgent: false,
    component: "Network",
    diagnosis: "DNS resolution failure",
    minerIdentifier: null,
    assigneeName: null,
    siteName: "Austin",
    buildingName: "Building 1",
    rackLabel: "",
    zone: "Zone 2",
    groupLabel: "",
    commentCount: 0,
    partsCount: 0,
    age: "0h",
  },
  {
    id: "17",
    ticketNumber: "TK-0017",
    category: "miner",
    status: "in_progress",
    urgent: false,
    component: "Hashboard",
    diagnosis: "Hashboard underperforming",
    minerIdentifier: "M0189",
    assigneeName: "Priya R.",
    siteName: "Miami",
    buildingName: "Building 4",
    rackLabel: "R08",
    zone: "Zone A",
    groupLabel: "Production",
    commentCount: 0,
    partsCount: 0,
    age: "2h",
  },
  {
    id: "18",
    ticketNumber: "TK-0018",
    category: "infrastructure",
    status: "open",
    urgent: false,
    component: "Building",
    diagnosis: "Roof leak above Zone 2",
    minerIdentifier: null,
    assigneeName: null,
    siteName: "Denver",
    buildingName: "Building 7",
    rackLabel: "",
    zone: "Zone 2",
    groupLabel: "",
    commentCount: 1,
    partsCount: 0,
    age: "5h",
  },
  {
    id: "19",
    ticketNumber: "TK-0019",
    category: "miner",
    status: "on_hold",
    urgent: true,
    component: "PSU",
    diagnosis: "PSU overvoltage fault",
    minerIdentifier: "M0222",
    assigneeName: "James T.",
    siteName: "Denver",
    buildingName: "Building 8",
    rackLabel: "R25",
    zone: "Zone B",
    groupLabel: "Production",
    commentCount: 2,
    partsCount: 0,
    age: "8h",
  },
  {
    id: "20",
    ticketNumber: "TK-0020",
    category: "infrastructure",
    status: "in_progress",
    urgent: false,
    component: "HVAC",
    diagnosis: "Exhaust fan maintenance",
    minerIdentifier: null,
    assigneeName: "Alex K.",
    siteName: "Marfa",
    buildingName: "Building 1",
    rackLabel: "",
    zone: "Zone 1",
    groupLabel: "",
    commentCount: 0,
    partsCount: 0,
    age: "14h",
  },
];

export const mockCompletedTickets = [
  {
    id: "101",
    ticketNumber: "TK-0101",
    component: "Fan",
    diagnosis: "Fan speed below threshold",
    minerIdentifier: "M0005",
    resolution: "Repaired",
    assigneeName: "Alex K.",
    completedAt: "2026-06-01",
    siteName: "Denver",
    buildingName: "Building 1",
  },
  {
    id: "102",
    ticketNumber: "TK-0102",
    component: "Hashboard",
    diagnosis: "Hashboard not detected",
    minerIdentifier: "M0019",
    resolution: "Replaced",
    assigneeName: "Maria S.",
    completedAt: "2026-06-02",
    siteName: "Austin",
    buildingName: "Building 2",
  },
  {
    id: "103",
    ticketNumber: "TK-0103",
    component: "PSU",
    diagnosis: "PSU overvoltage fault",
    minerIdentifier: "M0033",
    resolution: "Repaired",
    assigneeName: "James T.",
    completedAt: "2026-06-03",
    siteName: "Denver",
    buildingName: "Building 3",
  },
  {
    id: "104",
    ticketNumber: "TK-0104",
    component: "Control Board",
    diagnosis: "Control board unresponsive",
    minerIdentifier: "M0041",
    resolution: "Replaced",
    assigneeName: "Chen W.",
    completedAt: "2026-06-04",
    siteName: "Miami",
    buildingName: "Building 2",
  },
  {
    id: "105",
    ticketNumber: "TK-0105",
    component: "Network",
    diagnosis: "Switch port flapping",
    minerIdentifier: null,
    resolution: "Repaired",
    assigneeName: "Priya R.",
    completedAt: "2026-06-05",
    siteName: "Denver",
    buildingName: "Building 1",
  },
  {
    id: "106",
    ticketNumber: "TK-0106",
    component: "Fan",
    diagnosis: "Overheating — thermal throttle active",
    minerIdentifier: "M0058",
    resolution: "Repaired",
    assigneeName: "Alex K.",
    completedAt: "2026-06-05",
    siteName: "Austin",
    buildingName: "Building 1",
  },
  {
    id: "107",
    ticketNumber: "TK-0107",
    component: "Electrical",
    diagnosis: "PDU breaker tripped",
    minerIdentifier: null,
    resolution: "Repaired",
    assigneeName: "Maria S.",
    completedAt: "2026-06-06",
    siteName: "Miami",
    buildingName: "Building 10",
  },
  {
    id: "108",
    ticketNumber: "TK-0108",
    component: "Hashboard",
    diagnosis: "Hashboard underperforming",
    minerIdentifier: "M0072",
    resolution: "Deferred",
    assigneeName: "James T.",
    completedAt: "2026-06-07",
    siteName: "Denver",
    buildingName: "Building 5",
  },
  {
    id: "109",
    ticketNumber: "TK-0109",
    component: "HVAC",
    diagnosis: "Cooling loop pressure drop",
    minerIdentifier: null,
    resolution: "Repaired",
    assigneeName: "Chen W.",
    completedAt: "2026-06-08",
    siteName: "Austin",
    buildingName: "Building 3",
  },
  {
    id: "110",
    ticketNumber: "TK-0110",
    component: "Cleaning",
    diagnosis: "Dust filter replacement",
    minerIdentifier: null,
    resolution: "Repaired",
    assigneeName: "Priya R.",
    completedAt: "2026-06-08",
    siteName: "Denver",
    buildingName: "Building 2",
  },
];

export const mockInventoryParts = [
  {
    id: "1",
    name: "Fan Filter (120mm)",
    type: "Fan",
    siteName: "Denver",
    onHand: 45,
    allocated: 12,
    reorderPoint: 20,
    binLocation: "A1-03",
  },
  {
    id: "2",
    name: "Hashboard S21",
    type: "Hashboard",
    siteName: "Denver",
    onHand: 8,
    allocated: 5,
    reorderPoint: 10,
    binLocation: "B2-01",
  },
  {
    id: "3",
    name: "APW12 PSU",
    type: "PSU",
    siteName: "Denver",
    onHand: 14,
    allocated: 3,
    reorderPoint: 5,
    binLocation: "C1-02",
  },
  {
    id: "4",
    name: "Control Board S21",
    type: "Control Board",
    siteName: "Denver",
    onHand: 3,
    allocated: 2,
    reorderPoint: 5,
    binLocation: "B3-01",
  },
  {
    id: "5",
    name: "Thermal Paste (tube)",
    type: "Consumable",
    siteName: "Denver",
    onHand: 62,
    allocated: 0,
    reorderPoint: 20,
    binLocation: "D1-05",
  },
  {
    id: "6",
    name: "Heatsink S21",
    type: "Heatsink",
    siteName: "Denver",
    onHand: 18,
    allocated: 4,
    reorderPoint: 8,
    binLocation: "B2-03",
  },
  {
    id: "7",
    name: "Ethernet Cable (2m)",
    type: "Cable",
    siteName: "Denver",
    onHand: 120,
    allocated: 0,
    reorderPoint: 30,
    binLocation: "D2-01",
  },
  {
    id: "8",
    name: "Fan Filter (120mm)",
    type: "Fan",
    siteName: "Austin",
    onHand: 32,
    allocated: 8,
    reorderPoint: 20,
    binLocation: "A1-01",
  },
  {
    id: "9",
    name: "Hashboard S21",
    type: "Hashboard",
    siteName: "Austin",
    onHand: 4,
    allocated: 3,
    reorderPoint: 10,
    binLocation: "B1-02",
  },
  {
    id: "10",
    name: "APW12 PSU",
    type: "PSU",
    siteName: "Austin",
    onHand: 7,
    allocated: 1,
    reorderPoint: 5,
    binLocation: "C1-01",
  },
  {
    id: "11",
    name: "Control Board S21",
    type: "Control Board",
    siteName: "Austin",
    onHand: 2,
    allocated: 1,
    reorderPoint: 5,
    binLocation: "B2-01",
  },
  {
    id: "12",
    name: "Fan Filter (120mm)",
    type: "Fan",
    siteName: "Miami",
    onHand: 28,
    allocated: 6,
    reorderPoint: 20,
    binLocation: "A1-02",
  },
  {
    id: "13",
    name: "Hashboard S21",
    type: "Hashboard",
    siteName: "Miami",
    onHand: 6,
    allocated: 2,
    reorderPoint: 10,
    binLocation: "B1-01",
  },
];

export const mockInfraDevices = [
  {
    id: "fan-aus-1-1",
    name: "Fan Unit 1",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Austin",
    buildingName: "Building 1",
    ipAddress: "10.0.2.201",
    status: "online",
    rpm: 3200,
    model: "Delta EFB1248VH",
    issues: 0,
    powerW: 120,
    temperatureC: 42,
    firmware: "v2.1.4",
    lastSeen: "Just now",
  },
  {
    id: "fan-aus-1-2",
    name: "Fan Unit 2",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Austin",
    buildingName: "Building 1",
    ipAddress: "10.0.2.202",
    status: "online",
    rpm: 3200,
    model: "Delta EFB1248VH",
    issues: 0,
    powerW: 118,
    temperatureC: 43,
    firmware: "v2.1.4",
    lastSeen: "Just now",
  },
  {
    id: "fan-aus-1-3",
    name: "Fan Unit 3",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Austin",
    buildingName: "Building 1",
    ipAddress: "10.0.2.203",
    status: "offline",
    rpm: 0,
    model: "Delta EFB1248VH",
    issues: 0,
    powerW: 0,
    temperatureC: null,
    firmware: "v2.1.4",
    lastSeen: "3d ago",
  },
  {
    id: "fan-aus-2-1",
    name: "Fan Unit 1",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Austin",
    buildingName: "Building 2",
    ipAddress: "10.0.2.211",
    status: "online",
    rpm: 3100,
    model: "Delta EFB0812EH",
    issues: 0,
    powerW: 115,
    temperatureC: 41,
    firmware: "v2.0.8",
    lastSeen: "Just now",
  },
  {
    id: "fan-aus-2-2",
    name: "Fan Unit 2",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Austin",
    buildingName: "Building 2",
    ipAddress: "10.0.2.212",
    status: "online",
    rpm: 3100,
    model: "Delta EFB0812EH",
    issues: 0,
    powerW: 116,
    temperatureC: 42,
    firmware: "v2.0.8",
    lastSeen: "Just now",
  },
  {
    id: "fan-den-1-1",
    name: "Fan Unit 1",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Denver",
    buildingName: "Building 1",
    ipAddress: "10.0.3.201",
    status: "online",
    rpm: 2800,
    model: "Nidec V12E12BMM9",
    issues: 0,
    powerW: 95,
    temperatureC: 38,
    firmware: "v3.0.1",
    lastSeen: "Just now",
  },
  {
    id: "fan-den-1-2",
    name: "Fan Unit 2",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Denver",
    buildingName: "Building 1",
    ipAddress: "10.0.3.202",
    status: "online",
    rpm: 2800,
    model: "Nidec V12E12BMM9",
    issues: 0,
    powerW: 95,
    temperatureC: 38,
    firmware: "v3.0.1",
    lastSeen: "Just now",
  },
  {
    id: "fan-den-2-1",
    name: "Fan Unit 1",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Denver",
    buildingName: "Building 2",
    ipAddress: "10.0.3.211",
    status: "online",
    rpm: 2900,
    model: "Nidec V12E12BMM9",
    issues: 0,
    powerW: 96,
    temperatureC: 39,
    firmware: "v3.0.1",
    lastSeen: "Just now",
  },
  {
    id: "fan-den-5-1",
    name: "Fan Unit 1",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Denver",
    buildingName: "Building 5",
    ipAddress: "10.0.3.251",
    status: "online",
    rpm: 2750,
    model: "Nidec V12E12BMM9",
    issues: 0,
    powerW: 94,
    temperatureC: 37,
    firmware: "v3.0.1",
    lastSeen: "Just now",
  },
  {
    id: "fan-den-5-2",
    name: "Fan Unit 2",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Denver",
    buildingName: "Building 5",
    ipAddress: "10.0.3.252",
    status: "degraded",
    rpm: 1200,
    model: "Nidec V12E12BMM9",
    issues: 1,
    powerW: 98,
    temperatureC: 45,
    firmware: "v3.0.1",
    lastSeen: "2h ago",
  },
  {
    id: "fan-mia-2-1",
    name: "Fan Unit 1",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Miami",
    buildingName: "Building 2",
    ipAddress: "10.0.4.211",
    status: "online",
    rpm: 3400,
    model: "Sunon PMD2412PMB",
    issues: 0,
    powerW: 130,
    temperatureC: 44,
    firmware: "v2.5.0",
    lastSeen: "Just now",
  },
  {
    id: "fan-mia-2-2",
    name: "Fan Unit 2",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Miami",
    buildingName: "Building 2",
    ipAddress: "10.0.4.212",
    status: "online",
    rpm: 3400,
    model: "Sunon PMD2412PMB",
    issues: 0,
    powerW: 130,
    temperatureC: 44,
    firmware: "v2.5.0",
    lastSeen: "Just now",
  },
  {
    id: "fan-mia-2-3",
    name: "Fan Unit 3",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Miami",
    buildingName: "Building 2",
    ipAddress: "10.0.4.213",
    status: "online",
    rpm: 3350,
    model: "Sunon PMD2412PMB",
    issues: 0,
    powerW: 128,
    temperatureC: 43,
    firmware: "v2.5.0",
    lastSeen: "Just now",
  },
  {
    id: "fan-mia-10-1",
    name: "Fan Unit 1",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Miami",
    buildingName: "Building 10",
    ipAddress: "10.0.4.301",
    status: "online",
    rpm: 3000,
    model: "Sunon PMD2412PMB",
    issues: 0,
    powerW: 125,
    temperatureC: 41,
    firmware: "v2.5.0",
    lastSeen: "Just now",
  },
  {
    id: "fan-mia-10-2",
    name: "Fan Unit 2",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Miami",
    buildingName: "Building 10",
    ipAddress: "10.0.4.302",
    status: "online",
    rpm: 3000,
    model: "Sunon PMD2412PMB",
    issues: 0,
    powerW: 125,
    temperatureC: 41,
    firmware: "v2.5.0",
    lastSeen: "Just now",
  },
  {
    id: "fan-mar-1-1",
    name: "Fan Unit 1",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Marfa",
    buildingName: "Building 1",
    ipAddress: "10.0.5.201",
    status: "online",
    rpm: 2600,
    model: "Delta EFB1248VH",
    issues: 0,
    powerW: 90,
    temperatureC: 35,
    firmware: "v2.1.4",
    lastSeen: "Just now",
  },
];
